export const GET_LIST_VIDEO = "GET_LIST_VIDEO";
export const GET_LIST_VIDEO_SUCCESS = "GET_LIST_VIDEO_SUCCESS";
export const GET_LIST_VIDEO_ERROR = "GET_LIST_VIDEO_ERROR";

export const OPEN_MODAL_DELETE_VIDEO = "OPEN_MODAL_DELETE_VIDEO";
export const CLOSE_MODAL_DELETE_VIDEO = "CLOSE_MODAL_DELETE_VIDEO";

export const DELETE_VIDEO = "DELETE_VIDEO";
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS";

export const OPEN_MODAL_ADD_VIDEO = "OPEN_MODAL_ADD_VIDEO";
export const CLOSE_MODAL_ADD_VIDEO = "CLOSE_MODAL_ADD_VIDEO";

export const ADD_VIDEO = "ADD_VIDEO";
export const ADD_VIDEO_SUCCESS = "ADD_VIDEO_SUCCESS";

export const SET_EDIT_VIDEO = "SET_EDIT_VIDEO";

export const EDIT_VIDEO = "EDIT_VIDEO";
export const EDIT_VIDEO_SUCCESS = "EDIT_VIDEO_SUCCESS";

export const CLOSE_GET_LIST_VIDEO_ERROR_MODAL = "CLOSE_GET_LIST_VIDEO_ERROR_MODAL";