export const GET_LIST_ASK = "GET_LIST_ASK";
export const GET_LIST_ASK_SUCCESS = "GET_LIST_ASK_SUCCESS";
export const GET_LIST_ASK_ERROR = "GET_LIST_ASK_ERROR";

export const OPEN_MODAL_DELETE_ASK = "OPEN_MODAL_DELETE_ASK";
export const CLOSE_MODAL_DELETE_ASK = "CLOSE_MODAL_DELETE_ASK";

export const DELETE_ASK = "DELETE_ASK";
export const DELETE_ASK_SUCCESS = "DELETE_ASK_SUCCESS";

export const OPEN_MODAL_EDIT_ASK = "OPEN_MODAL_EDIT_ASK";
export const CLOSE_MODAL_EDIT_ASK = "CLOSE_MODAL_EDIT_ASK";

export const SET_EDIT_ASK = "SET_EDIT_ASK";

export const EDIT_ASK = "EDIT_ASK";
export const EDIT_ASK_SUCCESS = "EDIT_ASK_SUCCESS";

export const CLOSE_GET_LIST_ASK_ERROR_MODAL = "CLOSE_GET_LIST_ASK_ERROR_MODAL";
