export const GET_LIST_LEARN = "GET_LIST_LEARN";
export const GET_LIST_LEARN_SUCCESS = "GET_LIST_LEARN_SUCCESS";
export const GET_LIST_LEARN_ERROR = "GET_LIST_LEARN_ERROR";

export const OPEN_MODAL_DELETE_LEARN = "OPEN_MODAL_DELETE_LEARN";
export const CLOSE_MODAL_DELETE_LEARN = "CLOSE_MODAL_DELETE_LEARN";

export const DELETE_LEARN = "DELETE_LEARN";
export const DELETE_LEARN_SUCCESS = "DELETE_LEARN_SUCCESS";

export const OPEN_MODAL_ADD_LEARN = "OPEN_MODAL_ADD_LEARN";
export const CLOSE_MODAL_ADD_LEARN = "CLOSE_MODAL_ADD_LEARN";

export const ADD_LEARN = "ADD_LEARN";
export const ADD_LEARN_SUCCESS = "ADD_LEARN_SUCCESS";

export const SET_EDIT_LEARN = "SET_EDIT_LEARN";

export const EDIT_LEARN = "EDIT_LEARN";
export const EDIT_LEARN_SUCCESS = "EDIT_LEARN_SUCCESS";

export const CLOSE_GET_LIST_LEARN_ERROR_MODAL = "CLOSE_GET_LIST_LEARN_ERROR_MODAL";
