export const REQUEST_RESET_PASSWORD ="REQUEST_RESET_PASSWORD";
export const REQUEST_RESET_PASSWORD_SUCCESS ="REQUEST_RESET_PASSWORD_SUCCESS"

export const RE_RESET_PASSWORD_ERROR = "RE_RESET_PASSWORD_ERROR";
export const CLOSE_RE_RESET_PASSWORD_ERROR_MODAL = "CLOSE_RE_RESET_PASSWORD_ERROR_MODAL";