export const GET_LIST_ACCOUNT = "GET_LIST_ACCOUNT";
export const GET_LIST_ACCOUNT_SUCCESS = "GET_LIST_ACCOUNT_SUCCESS";
export const GET_LIST_ACCOUNT_ERROR = "GET_LIST_ACCOUNT_ERROR";

export const OPEN_MODAL_DELETE_ACCOUNT = "OPEN_MODAL_DELETE_ACCOUNT";
export const CLOSE_MODAL_DELETE_ACCOUNT = "CLOSE_MODAL_DELETE_ACCOUNT";

export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";

export const CLOSE_GET_LIST_ACCOUNT_ERROR_MODAL = "CLOSE_GET_LIST_ACCOUNT_ERROR_MODAL";

export const OPEN_MODAL_ADD_ACCOUNT = "OPEN_MODAL_ADD_ACCOUNT";
export const CLOSE_MODAL_ADD_ACCOUNT = "CLOSE_MODAL_ADD_ACCOUNT";

export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const ADD_ACCOUNT_SUCCESS = "ADD_ACCOUNT_SUCCESS";

export const SET_EDIT_ACCOUNT = "SET_EDIT_ACCOUNT";

export const EDIT_ACCOUNT = "EDIT_ACCOUNT";
export const EDIT_ACCOUNT_SUCCESS = "EDIT_ACCOUNT_SUCCESS";