export const GET_LIST_STATISTIC = "GET_LIST_STATISTIC";
export const GET_LIST_STATISTIC_SUCCESS = "GET_LIST_STATISTIC_SUCCESS";
export const GET_LIST_STATISTIC_ERROR = "GET_LIST_STATISTIC_ERROR";

export const CLOSE_GET_LIST_STATISTIC_ERROR_MODAL = "CLOSE_GET_LIST_STATISTIC_ERROR_MODAL";
