export const ACCEPT_CREATE_PASSWORD ="ACCEPT_CREATE_PASSWORD";
export const ACCEPT_CREATE_PASSWORD_SUCCESS ="ACCEPT_CREATE_PASSWORD_SUCCESS"

export const AC_CREATE_PASSWORD_ERROR = "AC_CREATE_PASSWORD_ERROR";
export const CLOSE_AC_CREATE_PASSWORD_ERROR_MODAL = "CLOSE_AC_CREATE_PASSWORD_ERROR_MODAL";